
default: &default
  adapter: postgresql
  encoding: utf8 #unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: localhost

  # Credenciales locales sin docker
  port: 5432
  username: alexis
  password: Aa.040292

  database: porfolio_development

# Warning: The database defined as "test" will be erased and

#production:
#  <<: *default
#  database: porfolio_production
#  username: porfolio
#  password: <%= ENV["PORFOLIO_DATABASE_PASSWORD"] %>


